services:
  api:
    image: avatars-api
    build:
      context: .
      target: dev
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - 5734:80

  web:
    image: avatars-web
    build:
      context: .
      target: dev
      dockerfile: ./web/Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - 5735:5173
